---
# Checkov configuration file
# https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html

# Directories to scan
directory:
  - iac

# Output format (can be cli, json, junitxml, github_failed_only, or sarif)
output: cli

# Skip specific checks
skip-check:
  # Add any checks you want to skip here, for example:
  # - CKV_AWS_1  # S3 Bucket has an ACL defined which allows public READ access
  - ALL  # Temporarily skip all checks

# Skip specific paths
skip-path:
  - iac/modules/bedrock-rag  # Skip the bedrock-rag module

# Quiet mode - only show failed checks
quiet: false

# Compact mode - reduce output verbosity
compact: false

# Show only failed checks
summary-position: bottom

# Framework to scan (terraform, cloudformation, kubernetes, all)
framework: terraform

# Temporarily disable enforcement - will show issues but not fail
soft-fail: true